import { readFile, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { confirmChanges, type IFileChange } from './diff-preview.ts';

/**
 * Shadcn -> Fumadocs variable mappings.
 * Each entry maps a bare Shadcn variable name to its `--color-fd-*` counterpart.
 */
const FUMADOCS_VARIABLE_MAPPINGS: Array<[string, string]> = [
  ['background', 'fd-background'],
  ['foreground', 'fd-foreground'],
  ['muted', 'fd-muted'],
  ['muted-foreground', 'fd-muted-foreground'],
  ['popover', 'fd-popover'],
  ['popover-foreground', 'fd-popover-foreground'],
  ['card', 'fd-card'],
  ['card-foreground', 'fd-card-foreground'],
  ['border', 'fd-border'],
  ['primary', 'fd-primary'],
  ['primary-foreground', 'fd-primary-foreground'],
  ['secondary', 'fd-secondary'],
  ['secondary-foreground', 'fd-secondary-foreground'],
  ['accent', 'fd-accent'],
  ['accent-foreground', 'fd-accent-foreground'],
  ['ring', 'fd-ring'],
  ['destructive', 'fd-destructive'],
  ['destructive-foreground', 'fd-destructive-foreground'],
  ['input', 'fd-input'],
];

const MARKER_COMMENT = '/* Fumadocs Theme Bridge — auto-generated by theme-manager-init */';

/**
 * Generates the CSS block that bridges Shadcn variables to Fumadocs `--color-fd-*` format.
 * @param layoutWidth - Optional fd-layout-width value.
 * @returns CSS string with :root and .dark blocks.
 */
export function generateFumadocsCssBlock(layoutWidth = '1400px'): string {
  const vars = FUMADOCS_VARIABLE_MAPPINGS
    .map(([shadcn, fd]) => `  --color-${fd}: var(--${shadcn});`)
    .join('\n');

  return [
    MARKER_COMMENT,
    ':root {',
    `  --fd-layout-width: ${layoutWidth};`,
    vars,
    '}',
    '.dark {',
    `  --fd-layout-width: ${layoutWidth};`,
    vars,
    '}',
  ].join('\n');
}

/**
 * Injects the Fumadocs CSS bridge into a project's CSS file.
 * Shows a diff preview and asks for confirmation before writing.
 * Idempotent — skips if the marker comment already exists.
 * Inserts before `@theme inline` so the bridge overrides `fumadocs-ui/css/neutral.css` defaults.
 * @param cwd - Project root directory.
 * @param cssFile - Relative path to the CSS file.
 * @returns Injection result status.
 */
export async function injectFumadocsBridge(
  cwd: string,
  cssFile: string,
): Promise<'injected' | 'already-present' | 'no-insertion-point' | 'declined'> {
  const fullPath = join(cwd, cssFile);
  const content = await readFile(fullPath, 'utf-8');

  if (content.includes(MARKER_COMMENT)) {
    return 'already-present';
  }

  const themeInlineIndex = content.indexOf('@theme inline');
  if (themeInlineIndex === -1) {
    return 'no-insertion-point';
  }

  const bridge = generateFumadocsCssBlock();
  const before = content.slice(0, themeInlineIndex);
  const after = content.slice(themeInlineIndex);
  const updated = before + bridge + '\n\n' + after;

  const changes: IFileChange[] = [
    { filePath: fullPath, oldContent: content, newContent: updated },
  ];

  const confirmed = await confirmChanges(changes);
  if (!confirmed) return 'declined';

  await writeFile(fullPath, updated, 'utf-8');
  return 'injected';
}
